export const INPUT_SEARCH_TEXT = 'INPUT_SEARCH_TEXT';
export const CLEAN_SEARCH_TEXT = 'CLEAN_SEARCH_TEXT';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const SET_FILTERS_LIST_VALUES = 'SET_FILTERS_LIST_VALUES';
export const TOGGLE_FOOTER = 'TOGGLE_FOOTER';
export const SAVE_SEARCH_RESULTS = 'SAVE_SEARCH_RESULTS';
export const SAVE_DATE_RESULTS = 'SAVE_DATE_RESULTS';
